# Generated by Django 4.1.2 on 2022-10-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_message_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='default_language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
